QUESTION 1

In [1]:
# package imports

In [2]:
import csv

In [3]:
# classes

In [4]:
class CSV:

    categories = []
    rows = []
    
    def __init__(self, file):
        self.file = file
        
    def __str__(self):
        return f'{self.file}'
        
    def __repr__(self):
        return f'a class to handle the import and reading of CSV files, in this instance: {self.file}'
        
    def read(file):
        with open(f'{file}.csv', 'r') as csvfile:

            csvreader = csv.reader(csvfile)
            categories = next(csvreader)
            rows = []

            for row in csvreader:
                rows.append(row)
        return(categories, rows)
            
    def rows_total(file):
        with open(f'{file}.csv', 'r') as csvfile:

            csvreader = csv.reader(csvfile)
            categories = next(csvreader)
            rows = []

            for row in csvreader:
                rows.append(row)
        print('Rows Total: %d' % (csvreader.line_num))
        
    def categories(file):
        with open(f'{file}.csv', 'r') as csvfile:

            csvreader = csv.reader(csvfile)
            categories = next(csvreader)
            rows = []

            for row in csvreader:
                rows.append(row)
        print('Fields:' + ', '.join(category for category in categories))
        
    def beginning(file, num_rows = 5):
        with open(f'{file}.csv', 'r') as csvfile:

            csvreader = csv.reader(csvfile)
            categories = next(csvreader)
            rows = []

            for row in csvreader:
                rows.append(row)
                
        print(f'\nFirst {num_rows} Rows:\n')
        
        for row in rows[:int(f'{num_rows}')]:
            for column in row:
                print('%10s' % column, end = ' '),
            print('\n')
            
    def end(file, num_rows = 5):
        with open(f'{file}.csv', 'r') as csvfile:

            csvreader = csv.reader(csvfile)
            categories = next(csvreader)
            rows = []

            for row in csvreader:
                rows.append(row)
                
        print(f'\nLast {num_rows} Rows:\n')
        
        for row in rows[-int(f'{num_rows}'):]:
            for column in row:
                print('%10s' % column, end = ' '),
            print('\n')
    def create_table(file):
        with open(f'{file}.csv', 'r') as csvfile:
            csvreader = csv.DictReader(csvfile)
        
            data_table = []
        
            for row in csvreader:
                data_table.append(row)
        
        for row in data_table:
            print(row)
            

df_iris = CSV('Iris')
df_housing = CSV('HousingPrices')

In [5]:
# testing / sanity checks

In [6]:
df_iris.read()

(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species'],
 [['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
  ['4.9', '3', '1.4', '0.2', 'Iris-setosa'],
  ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
  ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
  ['5', '3.6', '1.4', '0.2', 'Iris-setosa'],
  ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
  ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
  ['5', '3.4', '1.5', '0.2', 'Iris-setosa'],
  ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
  ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
  ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
  ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
  ['4.8', '3', '1.4', '0.1', 'Iris-setosa'],
  ['4.3', '3', '1.1', '0.1', 'Iris-setosa'],
  ['5.8', '4', '1.2', '0.2', 'Iris-setosa'],
  ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
  ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
  ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
  ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
  ['5.1', '3.8', '1.5', '0.3', 'Iris-se

In [7]:
df_housing.read()

(['SquareFeet', 'SalePrice'],
 [['1710', '208500'],
  ['1262', '181500'],
  ['1786', '223500'],
  ['1717', '140000'],
  ['2198', '250000'],
  ['1362', '143000'],
  ['1694', '307000'],
  ['2090', '200000'],
  ['1774', '129900'],
  ['1077', '118000'],
  ['1040', '129500'],
  ['2324', '345000'],
  ['912', '144000'],
  ['1494', '279500'],
  ['1253', '157000'],
  ['854', '132000'],
  ['1004', '149000'],
  ['1296', '90000'],
  ['1114', '159000'],
  ['1339', '139000'],
  ['2376', '325300'],
  ['1108', '139400'],
  ['1795', '230000'],
  ['1060', '129900'],
  ['1060', '154000'],
  ['1600', '256300'],
  ['900', '134800'],
  ['1704', '306000'],
  ['1600', '207500'],
  ['520', '68500'],
  ['1317', '40000'],
  ['1228', '149350'],
  ['1234', '179900'],
  ['1700', '165500'],
  ['1561', '277500'],
  ['2452', '309000'],
  ['1097', '145000'],
  ['1297', '153000'],
  ['1057', '109000'],
  ['1152', '82000'],
  ['1324', '160000'],
  ['1328', '170000'],
  ['884', '144000'],
  ['938', '130250'],
  ['1150', '

In [8]:
df_iris.rows_total()

Rows Total: 151


In [9]:
df_housing.rows_total()

Rows Total: 1461


In [10]:
df_iris.categories()

Fields:SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species


In [11]:
df_housing.categories()

Fields:SquareFeet, SalePrice


In [12]:
df_iris.beginning(10)


First 10 Rows:

       5.1        3.5        1.4        0.2 Iris-setosa 

       4.9          3        1.4        0.2 Iris-setosa 

       4.7        3.2        1.3        0.2 Iris-setosa 

       4.6        3.1        1.5        0.2 Iris-setosa 

         5        3.6        1.4        0.2 Iris-setosa 

       5.4        3.9        1.7        0.4 Iris-setosa 

       4.6        3.4        1.4        0.3 Iris-setosa 

         5        3.4        1.5        0.2 Iris-setosa 

       4.4        2.9        1.4        0.2 Iris-setosa 

       4.9        3.1        1.5        0.1 Iris-setosa 



In [13]:
df_housing.beginning(10)


First 10 Rows:

      1710     208500 

      1262     181500 

      1786     223500 

      1717     140000 

      2198     250000 

      1362     143000 

      1694     307000 

      2090     200000 

      1774     129900 

      1077     118000 



In [14]:
df_iris.end(10)


Last 10 Rows:

       6.7        3.1        5.6        2.4 Iris-virginica 

       6.9        3.1        5.1        2.3 Iris-virginica 

       5.8        2.7        5.1        1.9 Iris-virginica 

       6.8        3.2        5.9        2.3 Iris-virginica 

       6.7        3.3        5.7        2.5 Iris-virginica 

       6.7          3        5.2        2.3 Iris-virginica 

       6.3        2.5          5        1.9 Iris-virginica 

       6.5          3        5.2          2 Iris-virginica 

       6.2        3.4        5.4        2.3 Iris-virginica 

       5.9          3        5.1        1.8 Iris-virginica 



In [15]:
df_housing.end(10)


Last 10 Rows:

      1792     136000 

      1578     287090 

      1072     145000 

      1140      84500 

      1221     185000 

      1647     175000 

      2073     210000 

      2340     266500 

      1078     142125 

      1256     147500 



In [16]:
df_iris.create_table()

{'SepalLengthCm': '5.1', 'SepalWidthCm': '3.5', 'PetalLengthCm': '1.4', 'PetalWidthCm': '0.2', 'Species': 'Iris-setosa'}
{'SepalLengthCm': '4.9', 'SepalWidthCm': '3', 'PetalLengthCm': '1.4', 'PetalWidthCm': '0.2', 'Species': 'Iris-setosa'}
{'SepalLengthCm': '4.7', 'SepalWidthCm': '3.2', 'PetalLengthCm': '1.3', 'PetalWidthCm': '0.2', 'Species': 'Iris-setosa'}
{'SepalLengthCm': '4.6', 'SepalWidthCm': '3.1', 'PetalLengthCm': '1.5', 'PetalWidthCm': '0.2', 'Species': 'Iris-setosa'}
{'SepalLengthCm': '5', 'SepalWidthCm': '3.6', 'PetalLengthCm': '1.4', 'PetalWidthCm': '0.2', 'Species': 'Iris-setosa'}
{'SepalLengthCm': '5.4', 'SepalWidthCm': '3.9', 'PetalLengthCm': '1.7', 'PetalWidthCm': '0.4', 'Species': 'Iris-setosa'}
{'SepalLengthCm': '4.6', 'SepalWidthCm': '3.4', 'PetalLengthCm': '1.4', 'PetalWidthCm': '0.3', 'Species': 'Iris-setosa'}
{'SepalLengthCm': '5', 'SepalWidthCm': '3.4', 'PetalLengthCm': '1.5', 'PetalWidthCm': '0.2', 'Species': 'Iris-setosa'}
{'SepalLengthCm': '4.4', 'SepalWidthCm

In [17]:
df_housing.create_table()

{'SquareFeet': '1710', 'SalePrice': '208500'}
{'SquareFeet': '1262', 'SalePrice': '181500'}
{'SquareFeet': '1786', 'SalePrice': '223500'}
{'SquareFeet': '1717', 'SalePrice': '140000'}
{'SquareFeet': '2198', 'SalePrice': '250000'}
{'SquareFeet': '1362', 'SalePrice': '143000'}
{'SquareFeet': '1694', 'SalePrice': '307000'}
{'SquareFeet': '2090', 'SalePrice': '200000'}
{'SquareFeet': '1774', 'SalePrice': '129900'}
{'SquareFeet': '1077', 'SalePrice': '118000'}
{'SquareFeet': '1040', 'SalePrice': '129500'}
{'SquareFeet': '2324', 'SalePrice': '345000'}
{'SquareFeet': '912', 'SalePrice': '144000'}
{'SquareFeet': '1494', 'SalePrice': '279500'}
{'SquareFeet': '1253', 'SalePrice': '157000'}
{'SquareFeet': '854', 'SalePrice': '132000'}
{'SquareFeet': '1004', 'SalePrice': '149000'}
{'SquareFeet': '1296', 'SalePrice': '90000'}
{'SquareFeet': '1114', 'SalePrice': '159000'}
{'SquareFeet': '1339', 'SalePrice': '139000'}
{'SquareFeet': '2376', 'SalePrice': '325300'}
{'SquareFeet': '1108', 'SalePrice': '

QUESTION 2

In [18]:
# package imports

In [39]:
import numpy as np 
import pandas as pd

In [40]:
# variables

In [46]:
df_iris = pd.read_csv('Iris.csv')
df_housing = pd.read_csv('HousingPrices.csv')

In [42]:
# pandas function

In [51]:
def concatenate_df(dataframe1, dataframe2):
    
    ans = pd.concat([dataframe1, dataframe2], axis=0, ignore_index = True)
    
    rows = len(ans.axes[0])
    columns = len(ans.axes[1])
    
    size = f'''rows: {rows}
    columns: {columns}'''

    print(size)

    return ans


concat_df = concatenate_df(df_iris, df_housing)

concat_df

rows: 1610
    columns: 7


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0               5.1           3.5            1.4           0.2  Iris-setosa   
1               4.9           3.0            1.4           0.2  Iris-setosa   
2               4.7           3.2            1.3           0.2  Iris-setosa   
3               4.6           3.1            1.5           0.2  Iris-setosa   
4               5.0           3.6            1.4           0.2  Iris-setosa   
...             ...           ...            ...           ...          ...   
1605            NaN           NaN            NaN           NaN          NaN   
1606            NaN           NaN            NaN           NaN          NaN   
1607            NaN           NaN            NaN           NaN          NaN   
1608            NaN           NaN            NaN           NaN          NaN   
1609            NaN           NaN            NaN           NaN          NaN   

      SquareFeet  SalePrice  
0            NaN        NaN  
1            NaN        NaN  
2            NaN        NaN  
3            NaN        NaN  
4            NaN        NaN  
...          ...        ...  
1605      1647.0   175000.0  
1606      2073.0   210000.0  
1607      2340.0   266500.0  
1608      1078.0   142125.0  
1609      1256.0   147500.0  

[1610 rows x 7 columns]

In [ ]:
# NumPy function

In [21]:
# testing / sanity checks

QUESTION 3

In [22]:
# package imports

In [23]:
import numpy as np

In [24]:
# arrays / lists

In [25]:
# generate a random NumPy array with 1000 elements

numpy_array = np.random.randint(0, 10000, 1000) 

# generate a new array containing the original values of numpy_array
# divided into sub-arrays of 5

divided_array = np.split(numpy_array, 200)

# generate an empty list to which the mean values of each sub-array of numpy_array
# will be appended

datamean = []

In [26]:
# functions

In [27]:
# a function to find the mean of a given array

def mean(array):
    
    mean = sum(array) / len(array) 

    ans = f'The mean value of this array is {mean}'

    print(ans)    # the mean value is printed out to the script
    return(mean)  # after which the mean value is then returned up the chain and stored

# a function to store the mean values of each nested array (divided_array) within the parent array (numpy_array)

def nested_array_mean_values(parent_array):
    
    for nested_array in parent_array:      # a for loop iterates through the parent array 
        nested_array = mean(nested_array)  # and converts each nested array to its given mean value
        datamean.append(nested_array)      # which is stored in the datamean list
        
    return datamean

# a function to find the minimum value within a given array

def minimum(array):
    
    minimum = np.inf  # the minimum variable defaults to the highest possible value
    
    for i in range(0, len(array)):  # a for loop iterates through the array,
        if array[i] < minimum:      # if the current iteration value is less than that of the current minimum variable
            minimum = array[i]      # the previous minimum variable is replaced with the current iteration value
    
    ans = f'''The minimum value is: {minimum}'''
    
    print(ans)       # minimum value is printed out to the script
    return minimum   # and returned up the chain to be stored

# a function to find the maximum value within a given array

def maximum(array):

    maximum = -np.inf   # functions the same as the minimum(array) function,
    
    for i in range(0, len(array)):  # only the maximum variable defaults to the lowest possible value
        if array[i] > maximum:      # and the for loop checks if the current iteration value is greater
            maximum = array[i]      # than the current maximum variable value
    
    ans = f'''The maximum value is: {maximum}'''  
    
    print(ans)       # the for loop will finish with the maximum variable storing the highest value
    return maximum   # within the given array

In [28]:
# testing / sanity checks

In [29]:
numpy_array

array([ 515, 3438, 9803, 1726, 2124, 2922, 4658, 1049, 9901, 1347, 7432,
       6622, 1431, 9427, 6559, 5908, 1437, 3244, 4703, 1396, 6620, 3964,
       3333, 6366, 9553, 2484, 4436, 3133, 2207, 7379, 6996, 7614, 9249,
       1729, 7528, 6282, 3762, 5310, 5372, 3279,  832, 7629, 2274, 7614,
        237, 5496, 5416, 5389, 6143, 8473, 1545,  997, 6139, 7174, 9899,
       1988, 4219, 6010, 3148, 2034, 7812, 2195, 8122, 9908,  162, 2204,
       8183,  642, 7584, 6507, 6968,  294, 3209,  828, 5588, 9149, 9525,
       5836, 1726, 2325, 8178, 6203, 4174, 6717, 4498,  158, 2735, 3097,
       1859, 6682, 6753, 9835, 8250, 2491, 1344, 8700, 5496, 7880, 2076,
       5154, 5337, 7126, 2619, 6407, 3609, 9079, 9230, 7700, 8447, 8585,
       7569, 4136, 3576, 7951, 1574, 4193, 4463, 1815, 4648, 7102, 5928,
       6438, 4422, 3253,  522, 2581, 4233,  977, 2315, 6316, 1734, 7556,
       1521, 8041, 7223, 6032, 9004, 8506, 6234, 8188, 1957, 4858, 2445,
       7701, 5004, 8187,  743, 6303,  802, 4978, 18

In [30]:
divided_array

[array([ 515, 3438, 9803, 1726, 2124]),
 array([2922, 4658, 1049, 9901, 1347]),
 array([7432, 6622, 1431, 9427, 6559]),
 array([5908, 1437, 3244, 4703, 1396]),
 array([6620, 3964, 3333, 6366, 9553]),
 array([2484, 4436, 3133, 2207, 7379]),
 array([6996, 7614, 9249, 1729, 7528]),
 array([6282, 3762, 5310, 5372, 3279]),
 array([ 832, 7629, 2274, 7614,  237]),
 array([5496, 5416, 5389, 6143, 8473]),
 array([1545,  997, 6139, 7174, 9899]),
 array([1988, 4219, 6010, 3148, 2034]),
 array([7812, 2195, 8122, 9908,  162]),
 array([2204, 8183,  642, 7584, 6507]),
 array([6968,  294, 3209,  828, 5588]),
 array([9149, 9525, 5836, 1726, 2325]),
 array([8178, 6203, 4174, 6717, 4498]),
 array([ 158, 2735, 3097, 1859, 6682]),
 array([6753, 9835, 8250, 2491, 1344]),
 array([8700, 5496, 7880, 2076, 5154]),
 array([5337, 7126, 2619, 6407, 3609]),
 array([9079, 9230, 7700, 8447, 8585]),
 array([7569, 4136, 3576, 7951, 1574]),
 array([4193, 4463, 1815, 4648, 7102]),
 array([5928, 6438, 4422, 3253,  522]),


In [31]:
datamean

[]

In [32]:
nested_array_mean_values(divided_array)

datamean

The mean value of this array is 3521.2
The mean value of this array is 3975.4
The mean value of this array is 6294.2
The mean value of this array is 3337.6
The mean value of this array is 5967.2
The mean value of this array is 3927.8
The mean value of this array is 6623.2
The mean value of this array is 4801.0
The mean value of this array is 3717.2
The mean value of this array is 6183.4
The mean value of this array is 5150.8
The mean value of this array is 3479.8
The mean value of this array is 5639.8
The mean value of this array is 5024.0
The mean value of this array is 3377.4
The mean value of this array is 5712.2
The mean value of this array is 5954.0
The mean value of this array is 2906.2
The mean value of this array is 5734.6
The mean value of this array is 5861.2
The mean value of this array is 5019.6
The mean value of this array is 8608.2
The mean value of this array is 4961.2
The mean value of this array is 4444.2
The mean value of this array is 4112.6
The mean value of this ar

[3521.2,
 3975.4,
 6294.2,
 3337.6,
 5967.2,
 3927.8,
 6623.2,
 4801.0,
 3717.2,
 6183.4,
 5150.8,
 3479.8,
 5639.8,
 5024.0,
 3377.4,
 5712.2,
 5954.0,
 2906.2,
 5734.6,
 5861.2,
 5019.6,
 8608.2,
 4961.2,
 4444.2,
 4112.6,
 3284.4,
 5215.0,
 7592.8,
 4393.0,
 4202.6,
 4273.2,
 7351.0,
 5737.4,
 8081.0,
 4773.2,
 7457.6,
 4211.4,
 4830.2,
 4441.0,
 5176.6,
 6338.2,
 5490.8,
 5181.8,
 4112.8,
 4592.2,
 4454.6,
 5962.4,
 6703.6,
 4728.0,
 5181.6,
 4606.8,
 4978.8,
 4714.0,
 3979.0,
 6592.6,
 4605.2,
 4719.8,
 6516.0,
 5497.0,
 6758.6,
 6713.6,
 3086.2,
 5624.4,
 6468.6,
 4622.8,
 4528.0,
 3098.6,
 6790.8,
 4843.2,
 7480.0,
 3779.0,
 5543.0,
 2904.4,
 3382.4,
 4466.0,
 6782.0,
 4974.0,
 5563.8,
 6175.6,
 3928.8,
 5290.8,
 3086.2,
 2965.8,
 4557.2,
 5051.8,
 4491.8,
 2602.0,
 6269.0,
 5142.8,
 7812.6,
 5062.2,
 5218.4,
 5949.6,
 3524.0,
 5361.0,
 5397.6,
 3152.6,
 5691.4,
 6304.8,
 6607.4,
 5192.6,
 4422.8,
 5656.4,
 5431.4,
 4919.4,
 4664.4,
 5313.2,
 6351.2,
 4132.6,
 4234.4,
 3850.2,
 

In [33]:
datamean

[3521.2,
 3975.4,
 6294.2,
 3337.6,
 5967.2,
 3927.8,
 6623.2,
 4801.0,
 3717.2,
 6183.4,
 5150.8,
 3479.8,
 5639.8,
 5024.0,
 3377.4,
 5712.2,
 5954.0,
 2906.2,
 5734.6,
 5861.2,
 5019.6,
 8608.2,
 4961.2,
 4444.2,
 4112.6,
 3284.4,
 5215.0,
 7592.8,
 4393.0,
 4202.6,
 4273.2,
 7351.0,
 5737.4,
 8081.0,
 4773.2,
 7457.6,
 4211.4,
 4830.2,
 4441.0,
 5176.6,
 6338.2,
 5490.8,
 5181.8,
 4112.8,
 4592.2,
 4454.6,
 5962.4,
 6703.6,
 4728.0,
 5181.6,
 4606.8,
 4978.8,
 4714.0,
 3979.0,
 6592.6,
 4605.2,
 4719.8,
 6516.0,
 5497.0,
 6758.6,
 6713.6,
 3086.2,
 5624.4,
 6468.6,
 4622.8,
 4528.0,
 3098.6,
 6790.8,
 4843.2,
 7480.0,
 3779.0,
 5543.0,
 2904.4,
 3382.4,
 4466.0,
 6782.0,
 4974.0,
 5563.8,
 6175.6,
 3928.8,
 5290.8,
 3086.2,
 2965.8,
 4557.2,
 5051.8,
 4491.8,
 2602.0,
 6269.0,
 5142.8,
 7812.6,
 5062.2,
 5218.4,
 5949.6,
 3524.0,
 5361.0,
 5397.6,
 3152.6,
 5691.4,
 6304.8,
 6607.4,
 5192.6,
 4422.8,
 5656.4,
 5431.4,
 4919.4,
 4664.4,
 5313.2,
 6351.2,
 4132.6,
 4234.4,
 3850.2,
 

In [34]:
len(datamean)

200

In [35]:
datamean_minimum = minimum(datamean)

The minimum value is: 1737.0


In [36]:
datamean_maximum = maximum(datamean)

The maximum value is: 8737.8


In [37]:
print(datamean_minimum)
print(datamean_maximum)

1737.0
8737.8


QUESTION 4