In [1]:
import pandas as pd
import numpy as np

In [2]:
numpy_array = np.random.randint(-10000, 10000, 1000)

In [3]:
def mean(array):
    X = sum(array) / len(array)

    ans = f'The mean value of this array is {X}'

    print(ans)
    return(X)

In [4]:
def minmax(array):
    
    minimum = np.inf
    maximum = -np.inf
    
    for i in range(0, len(array)):
        if array[i] < minimum:
            minimum = array[i]
    
    for j in range(0, len(array)):
        if array[j] > maximum:
            maximum = array[j]
    
    ans = f'''The minimum value is: {minimum}
The maximum value is: {maximum}'''
    
    print(ans)
    return minimum, maximum

In [5]:
print(numpy_array)

[-7012 -8766 -1760  3626 -2016 -2746  7979  8870  4122  5723 -2019  6875
  6905  9716 -2936  3311 -3739  5191  2128  1044  4966  7923  3177  3777
  5228 -7202  1158  2814  4178 -6587  2055  6649 -9437  6052  8950 -7816
 -2290 -4985  8899  -967  -770  6537  5280 -5401 -6851 -6390 -5620 -7614
 -6473 -4027 -3555  3634 -4852   137 -6278  4695 -3862 -2289  -346 -3191
 -9414  5885  3874 -5327  4784  7628  9196  6910  1231 -3612  -414 -3951
  5967 -6281  9200 -1284  2685  1008  3580  7484 -9645  2768 -2336 -7627
  1316  6773  7308  3578 -4045  9870  1708  4942 -5305  1024 -9975 -7603
  8145  -535 -4300 -8607 -5002 -4382 -6382 -5152  7147   699  5594 -6948
 -2492  6051  -108  9063  7065  3497 -2746 -5271 -3785  9865  1097  7219
  2181  2827  8546 -9889  8845 -6746 -9804   469 -3826  5785 -4085 -9890
 -9697 -8621  2347  2697 -6691  5911   376  2037 -8174  2819  2900 -3887
 -4055  5145  7588 -6545 -3662  9235  7730 -4393 -4929 -8086 -5878 -8349
 -7325 -1286 -7078 -5777  7081 -3660 -5312 -5194   

In [6]:
numpy_array_minmax = minmax(numpy_array)

The minimum value is: -9986
The maximum value is: 9994


In [7]:
numpy_array_minmax

(-9986, 9994)

In [8]:
print(min(numpy_array), max(numpy_array))

-9986 9994


In [9]:
numpy_array_mean = mean(numpy_array)
numpy_array_mean

The mean value of this array is 49.819


49.819

In [23]:
datamean = np.split(numpy_array, 200)

In [24]:
datamean

[array([-7012, -8766, -1760,  3626, -2016]),
 array([-2746,  7979,  8870,  4122,  5723]),
 array([-2019,  6875,  6905,  9716, -2936]),
 array([ 3311, -3739,  5191,  2128,  1044]),
 array([4966, 7923, 3177, 3777, 5228]),
 array([-7202,  1158,  2814,  4178, -6587]),
 array([ 2055,  6649, -9437,  6052,  8950]),
 array([-7816, -2290, -4985,  8899,  -967]),
 array([ -770,  6537,  5280, -5401, -6851]),
 array([-6390, -5620, -7614, -6473, -4027]),
 array([-3555,  3634, -4852,   137, -6278]),
 array([ 4695, -3862, -2289,  -346, -3191]),
 array([-9414,  5885,  3874, -5327,  4784]),
 array([ 7628,  9196,  6910,  1231, -3612]),
 array([ -414, -3951,  5967, -6281,  9200]),
 array([-1284,  2685,  1008,  3580,  7484]),
 array([-9645,  2768, -2336, -7627,  1316]),
 array([ 6773,  7308,  3578, -4045,  9870]),
 array([ 1708,  4942, -5305,  1024, -9975]),
 array([-7603,  8145,  -535, -4300, -8607]),
 array([-5002, -4382, -6382, -5152,  7147]),
 array([  699,  5594, -6948, -2492,  6051]),
 array([ -108, 